### ISSUE TITLE
Argument "" isn't numeric 

### ISSUE THREAD

**Issue by picklesrein** [moisseev/BackupPC_report#3]
Noticed an email contained a couple errors from the daily cronjobs on one of my BackupPC hosts this morning. Looking back it appears to happen several times per week:

`Cron <root@host> /usr/share/BackupPC/bin/BackupPC_report.pl -s | mail -E -r `hostname -s`@`hostname -d` -s "BackupPC@`hostname -s` warning" user@domain.com`

```
Argument "" isn't numeric in division (/) at /usr/share/BackupPC/bin/BackupPC_report.pl line 87.
Argument "" isn't numeric in subtraction (-) at /usr/share/BackupPC/bin/BackupPC_report.pl line 87.

```
Line 87 is the first use of `@Report`

```
        push @Report, [
            "",    # warning flags
            $_->{num},
```

**Comment by moisseev** [comment]
Actually, these errors could happen on any line of the `push` list, but the interpreter reports the number of the first line of the `push` function.
The issue should have been fixed with https://github.com/moisseev/BackupPC_report/commit/baad6296dc756fe246d728ebc9fe853e02d7dd41#diff-0a5be55ed25e36e1559f79ae4939f599
Would you test the latest version?

**Comment by picklesrein** [comment]
thanks for looking into it Alexander. I'm working on an Ansible script to pull the latest from the master branch.

**Comment by picklesrein** [comment]
Successfully built an Ansible script to pull then update the path prefix and push the code out to our backuppc servers. Works great!

```
---
- hosts: all
  name: Enable BackupPC error reports and weekly summaries
  gather_facts: False
  become: True
  tasks:

  - name: Get file from git repo
    become: False
    local_action:
      module: git
      repo: https://github.com/moisseev/BackupPC_report.git
      force: yes
      dest: /tmp/checkout_BackupPC_report/

  - name: Put BackupPC_report.pl in place
    copy:
      backup: yes
      src: /tmp/checkout_BackupPC_report/BackupPC_report
      dest: /usr/share/BackupPC/bin/BackupPC_report.pl
      owner: root
      group: root
      mode: 0755

  - name: edit BackupPC_report
    replace:
      regexp: "use lib '/usr/local/lib';.*"
      replace: "use lib '/usr/share/BackupPC/lib';    # <<< change path prefix to match your installation"
      path: /usr/share/BackupPC/bin/BackupPC_report.pl
      backup: no

  - name: add backuppc weekly report
    cron:
      user: root
      env: no
      name: "BackupPC - Send report Monday morning"
      weekday: 1
      minute: 05
      hour: 08
      job: '/usr/share/BackupPC/bin/BackupPC_report.pl | mail -r `hostname -s`@`hostname -d` -s "BackupPC@`hostname -s` weekly report" my_backup@domain.com'

  - name: add report on error
    cron:
      user: root
      env: no
      name: "BackupPC - Send report on error"
      minute: 05
      hour: 08
      job: '/usr/share/BackupPC/bin/BackupPC_report.pl -s | mail -E -r `hostname -s`@`hostname -d` -s "BackupPC@`hostname -s` warning" my_backup@domain.com'
...
```
